### ISSUE TITLE
Recent changes broke webmock CI

### ISSUE THREAD

**Issue by ojab** [aaronpowell/httpstatus#105]
See https://github.com/bblimke/webmock/pull/965 and https://github.com/bblimke/webmock/runs/4661798356?check_suite_focus=true
There is 301 to https:// on http:// requests (easy to fix), `X-Powered-By` is no longer in headers (easy to fix) and no `Content-Length` header (hard to fix).

Could you please tweak deployment to return `Content-Length`?

**Comment by aaronpowell** [comment]
Is there a reason for relying on the `http` not `https` scheme for the tests you run? I think I can disable the force HTTPS on Azure with a custom domain, but I'd kind of prefer not to, as there's not really a good reason to not be using HTTPS everywhere.

For the `X-Powered-By` header, that was coming from IIS and not the service, so when it moved from IIS to Docker as the hosting, it was dropped. Given that that's a non-standard header anyway, I would discourage reliance on it. Instead, you should rely on the `Server` header, as that is standard. In the .NET 6 version, the value of this header is `Kestrel`.

I'm unsure why the `Content-Length` header has been dropped though, it should be there, so I'll have to dig around to figure that one out.

**Comment by ojab** [comment]
`https` and `X-Powered-By` just used currently, it could be easily changed/fixed. `Content-Length` is a problem though. So if it could be added back — I could make a PR to fix the CI without dropping `httpstat.us`.

**Comment by aaronpowell** [comment]
I spoke with some engineers on aspnet and they pointed out that Kestrel uses `Transfer-Encoding: chunked` by default, and as a result of that over HTTP/1.1 it will send a blank `Content-Length` unless explicitly set (see https://github.com/dotnet/aspnetcore/blob/d5557cd2441ea5e81f298d35663949576836dd4d/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1145-L1171).

I've now set an explicit `Content-Length` with https://github.com/aaronpowell/httpstatus/commit/cb683b916a5a5fd4f79a4bf9b5f56f570ea8dae8 and tested it works:

```
➜ curl -H "Accept: application/json" --head https://httpstat.us/200
HTTP/1.1 200 OK
Content-Length: 31
Content-Type: application/json
Server: Kestrel
Request-Context: appId=cid-v1:1e93d241-20e4-4513-bbd7-f452a16a5d69
Strict-Transport-Security: max-age=2592000
Set-Cookie: ARRAffinity=c8fcc30ceb9d725a7f379f8837c91f9e4afa35242bd4fb5dcad86baef02d41ad;Path=/;HttpOnly;Secure;Domain=httpstat.us
Set-Cookie: ARRAffinitySameSite=c8fcc30ceb9d725a7f379f8837c91f9e4afa35242bd4fb5dcad86baef02d41ad;Path=/;HttpOnly;SameSite=None;Secure;Domain=httpstat.us
Date: Fri, 14 Jan 2022 04:19:03 GMT
```

Sorry about the breaking change, I'll add that to the notes of others to be aware of as I work on a blog post

**Comment by ojab** [comment]
Thanks! Got green CI run https://github.com/ojab/webmock/actions/runs/1696366879.
