### ISSUE TITLE
Subdomain status

### ISSUE THREAD

**Issue by bradyclifford** [aaronpowell/httpstatus#106]
In testing, usually the service request is being made to a path based route.

It would be create if this could be altered to a subdomain toggle for the status codes.

https://200.httpstatus.us/some-randome/path
https://503.httpstatus.us/some-randome/path

**Comment by aaronpowell** [comment]
I can see the point of what you're trying to achieve, but I'm not sure how technically feasible it'd be to implement. The app would need to not just be aware of the first segment of the path, but optionally aware of the subdomain and "fake" that as part of the path.

Then it begs the question, what would happen if you did `https://200.httpstat.us/500`, is that going to give you a 200 or a 500 response code?

The app does ignore anything in the path _after_ the status code provided, so you can do https://httpstat.us/200/some-random/path and get back a 200 response, so would it be possible in your scenarios to include set the "host" that's being injected to `https://httpstat.us/200` not just `https://httpstat.us`?

**Comment by bradyclifford** [comment]
Ya that makes sense.  I didn't realize you could have a wildcard path after the status code.

Yes what you are explaining I can implement as a workaround.  Currently my team is using the HttpClient.BaseAddress and setting it just to the host, allowing the client to default to `https` protocol.  So it is double to alter that.
