### ISSUE TITLE
allow --head/-I on https://httpstat.us

### ISSUE THREAD

**Issue by nschloe** [aaronpowell/httpstatus#107]
Since recently, [deadlink](https://github.com/nschloe/deadlink/) tests are failing because httpstat.us no longer accepts HEAD requests to https://httpstat.us
```
curl --head https://httpstat.us
```
```
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Length: 0
Server: Kestrel
Request-Context: appId=cid-v1:1e93d241-20e4-4513-bbd7-f452a16a5d69
Strict-Transport-Security: max-age=2592000
Set-Cookie: ARRAffinity=68e4a3f96ceee7f4512ef93d974d789a76ba44b2ab061595242907ccb9c1fd47;Path=/;HttpOnly;Secure;Domain=httpstat.us
Set-Cookie: ARRAffinitySameSite=68e4a3f96ceee7f4512ef93d974d789a76ba44b2ab061595242907ccb9c1fd47;Path=/;HttpOnly;SameSite=None;Secure;Domain=httpstat.us
Date: Wed, 09 Mar 2022 12:32:54 GMT
```
Is this intentional?

**Comment by aaronpowell** [comment]
@nschloe apologies but no, it should still support a HEAD method. I'll have a look at it and let you know when a fix is deployed

**Comment by aaronpowell** [comment]
Just had a look, it's only on the `/` route - https://github.com/aaronpowell/httpstatus/blob/main/src/Teapot.Web/Controllers/StatusController.cs#L17

`HEAD` works on the status code requests though. Is there a reason that you're hitting the home page in the tests?

**Comment by nschloe** [comment]
I build redirect chains and check if the last node is valid. `httpstat.us/301` redirects to `httpstat.us` which is why that check fails now.

**Comment by nschloe** [comment]
Thanks!
