### ISSUE TITLE
Add the ability to give a sleep parameter in headers

### ISSUE THREAD

**Issue by bra-fsn** [aaronpowell/httpstatus#109]
I would like to use httpstat.us for testing a proxy, which must fall back to the stored content if the upstream site can't be reached.
The best option for testing this would be to utilize the `?sleep=x` query, but the problem with that is that it's part of the URL, so I can't make it pass and then make it time out later.
So I think it would be great to be able to set the `sleep` parameter in a client header, for example by sending:
```
X-Sleep: 1000
```
in the HTTP request.
Could you please implement this?

**Comment by aaronpowell** [comment]
I'm not sure I understand how making it a header rather than a query string argument will make it more dynamic in setting on request

**Comment by bra-fsn** [comment]
> I'm not sure I understand how making it a header rather than a query string argument will make it more dynamic in setting on request
If the proxy takes query strings into account, the two URLs will be different:
http://httpstat.us/200?sleep=0
http://httpstat.us/200?sleep=30000
I would like to use it to test the scenario, where a response times out and the cache falls back to the stored content.
So if the `sleep` argument can be specified in the headers, I can cache the working version, then make a query to the timeout version and the two URLs will be the same.

**Comment by aaronpowell** [comment]
Ah, so you're caching on the full URL, not the host/path?
