### ISSUE TITLE
Redirect location should also return json if you pass json header

### ISSUE THREAD

**Issue by kmccarp** [aaronpowell/httpstatus#113]
If you make a request to `httpstat.us/308` and you get a location back, right now it's `httpstat.us/` which cannot return json.

I propose a version of this that sets `Location` to another status code, so that clients can test that their redirect logic keeps the correct headers.

Created a draft PR that just returns to `/200`, but could be configurable with a request param or header: https://github.com/aaronpowell/httpstatus/pull/112

**Comment by aaronpowell** [comment]
Sounds like a good idea, let me put some notes on the PR

**Comment by aaronpowell** [comment]
Closing as custom response headers can be provided, which would solve this.
