### ISSUE TITLE
https://httpstat.us/504 returns empty response 200

### ISSUE THREAD

**Issue by hajdukd** [aaronpowell/httpstatus#114]
Hi,

I've noticed the service responds with 200 on /504 endpoint. Seems like a regression.

**Comment by aaronpowell** [comment]
Please search the issue register, this is expected. See https://github.com/aaronpowell/httpstatus/issues/89

**Comment by sukolenvo** [comment]
Thanks for the service, it helps alot in testing. How about removing 504 from the list of supported codes if its disabled for the time being?
https://github.com/aaronpowell/httpstatus/blob/058d5b93178cb9f11d9aeb9405e07ef5875331c8/src/Teapot.Web/Models/TeapotStatusCodeResults.cs#L306-L309

Cheers

**Comment by aaronpowell** [comment]
I've reviewed the logs and it looks like it's no longer receiving abuse on that status code, so it's now enabled again
