### ISSUE TITLE
Accept application/json behavior change

### ISSUE THREAD

**Issue by dehli** [aaronpowell/httpstatus#116]
Previously, when you'd make a `POST` to https://httpstat.us/200 with `Accept` set to `application/json`, you'd receive a JSON response like:

```js
{
  "code": 200,
  "description": "OK"
}
```

With the recent changes, it seems to just be returning an empty body. I looked through the recent commits but nothing stood out to me. Let me know if the change was intentional and I can close this / update relevant docs. Thanks!

**Comment by aaronpowell** [comment]
Hmm, I'll have a look, but it should return a JSON payload.

**Comment by aaronpowell** [comment]
Sorry, I broke that yesterday when I refactored and set the default for `ExcludeBody` to `true`, meaning that most status codes stopped being able to generate JSON.

Maybe I should write some tests 🤣

**Comment by aaronpowell** [comment]
Fixed - sorry again!

**Comment by dehli** [comment]
Thanks & no need to apologize! Appreciate the time you put into maintaining this. Cheers!

**Comment by gk-brown** [comment]
Is it possible that the `Accept` header isn't forwarded for redirects? I am submitting a POST to https://httpstat.us/307 with the following headers:
```
Accept: application/json
Accept-Language: en-us
```

The POST body contains:
```
foo=bar
```

Ultimately I get a 200 response, but the content type (and payload) of the response is HTML.
