### ISSUE TITLE
JSON response returns text instead of JSON

### ISSUE THREAD

**Issue by eunicode** [aaronpowell/httpstatus#122]
When I make a POST request to the endpoint with JSON in the body and the header set to `'Content-Type': 'application/json'`, it seems I get a text response like `"200 OK"` instead of a JSON response like `{ "code": 200 }`. When I try to parse the response as JSON, I get the syntax error `Unexpected non-whitespace character after JSON at position 4`.

It seems it was fixed here [Accept application/json behavior change #116](https://github.com/aaronpowell/httpstatus/issues/116) but perhaps the issue has resurfaced.

**Comment by aaronpowell** [comment]
You've mixed up the `Content-Type` and `Accept` headers. `Content-Type` is used in indicate the incoming media type (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) whereas `Accept` is used in indicate the supported response types (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept).

To let httpstat.us know that you want JSON as a response you need to have `application/json` in the `Accept` header so https://github.com/aaronpowell/httpstatus/blob/main/src/Teapot.Web/CustomHttpStatusCodeResult.cs#L62 is triggered.
