### ISSUE TITLE
5xx Error

### ISSUE THREAD

**Issue by dehli** [aaronpowell/httpstatus#124]
Hello, thanks again for maintaining this! Wanted to let you know that the hosted API is returning 503s for all requests.

**Comment by dehli** [comment]
Closing as the issue has resolved itself. :tada:

**Comment by dehli** [comment]
Reopening b/c it looks like the error is back.

**Comment by trymoto** [comment]
Yep can cofirm 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/2513899/217074598-c6d1c210-a64f-4716-b209-9b42b08bd5a6.png">

**Comment by aaronpowell** [comment]
Looks all good again, I'll go check out the Azure logs.
