### ISSUE TITLE
Service is down. httpstat.us/200 returns a 502

### ISSUE THREAD

**Issue by jackstephenson96** [aaronpowell/httpstatus#131]

**Comment by aaronpowell** [comment]
Yep, hit a huge traffic spike (~800k requests in the space of a few minutes).

Looks like the abuse has abated.

**Comment by jackstephenson96** [comment]
Oof, sorry to hear that! Appreciate the follow up.Best,JackOn Apr 26, 2023, at 8:54 PM, Aaron Powell ***@***.***> wrote:﻿
Yep, hit a huge traffic spike (~800k requests in the space of a few minutes).
Looks like the abuse has abated.
