### ISSUE TITLE
Support excluding body via a request parameter

### ISSUE THREAD

**Issue by DamianEdwards** [aaronpowell/httpstatus#132]
Would be nice to force exclusion of the body via a bindable request parameter (header, query string, etc.)

**Comment by neilboyd** [comment]
I'm curious why you would want this. You're asking for an invalid HTTP response.

**Comment by neilboyd** [comment]
Okay, so maybe it's not technically invalid, but it's not recommended and some clients may get confused, but I suppose that's the point of this test server ;)
