### ISSUE TITLE
Status code "307" doesn't work

### ISSUE THREAD

**Issue by travisTheOrange** [aaronpowell/httpstatus#143]
When using Postman (or one's browser) if you try the following URL, `https://httpstat.us/307`, you get redirected to the sites main page. Even though most of other 300's work.

**Comment by aaronpowell** [comment]
That's correct, a 307 is a [temporary redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) and will redirect to the `Location` header provided, if the caller is set to follow redirects (which browsers do).
