### ISSUE TITLE
The three link examples on the page don’t link to anything

### ISSUE THREAD

**Issue by nclm** [aaronpowell/httpstatus#148]
These links are missing an href attribute:

```html
Just add the status code you want to the URL, like this:
<a href="">httpstat.us/200</a>
```

```html
for example
<a href="">httpstat.us/random/200,201,500-504</a>.
```

```html
like this:
<a href="">httpstat.us/200?sleep=5000</a>
```

Should be:

```html
Just add the status code you want to the URL, like this:
<a href="https://httpstat.us/200">httpstat.us/200</a>
```

```html
for example
<a href="https://httpstat.us/random/200,201,500-504">httpstat.us/random/200,201,500-504</a>.
```

```html
like this:
<a href="https://httpstat.us/200?sleep=5000">httpstat.us/200?sleep=5000</a>
```

**Comment by nclm** [comment]
I wanted to make a pull request but it turns out these links are not HTML in the code but generated by some syntax I don’t recognise:

https://github.com/aaronpowell/httpstatus/blob/29baee85ab420c6515303f732947636cc8bb7fdd/src/Teapot.Web/Pages/Index.cshtml#L10

https://github.com/aaronpowell/httpstatus/blob/29baee85ab420c6515303f732947636cc8bb7fdd/src/Teapot.Web/Pages/Index.cshtml#L30

https://github.com/aaronpowell/httpstatus/blob/29baee85ab420c6515303f732947636cc8bb7fdd/src/Teapot.Web/Pages/Index.cshtml#L36

**Comment by aaronpowell** [comment]
Nice catch - that'd be a hold-over from before it was using minimal API and I don't think those HtmlHelpers did what was required anymore so I've removed them for standard `<a>` tags.
