### ISSUE TITLE
Random status (OK/BAD)

### ISSUE THREAD

**Issue by OsoianMarcel** [aaronpowell/httpstatus#70]
Hello,

Would be great to have an endpoint which will return random statuses.
For example:
/random/200-500
or /random?list=200,400,500
or /succces-or-failure (For ex.: 200 or 500)

**Comment by petemhdroplet** [comment]
I have created a pull request for a failChance parameter which will return a 500 instead of the specified status every 1 in x requests

**Comment by bradyclifford** [comment]
Would be great if it would return a 503 or 504 instead of a 500.   Or perhaps add the ability to suggest what type of failure occurs randomly.
