### ISSUE TITLE
Containerized httpstatus

### ISSUE THREAD

**Issue by jenciso** [aaronpowell/httpstatus#95]
Hi.

Is there some Dockerfile to build httpstatus as a container image?

**Comment by tathamoddie** [comment]
Not yet, but sounds like a great idea for easier local hosting. 👍

**Comment by mderriey** [comment]
There's an open PR to migrate the app to .NET Core which would greatly simplify building a Docker image.

See #91

**Comment by kcootedinh** [comment]
Would love to see an ASP.NET Core version

**Comment by aaronpowell** [comment]
We have it containerised, I just need to find some time to push it and migrate to it

**Comment by TommasoBianchi** [comment]
Hi @aaronpowell, any news on this? It looks like a great project to me and would love to be able to self-deploy in a Kubernetes cluster to test various timeout-related ingress configurations.

**Comment by aaronpowell** [comment]
I've just finished upgrading to .NET 6, and in doing so, it's now containerised. To Dockerfile is here https://github.com/Readify/httpstatus/blob/main/src/Teapot.Web/Dockerfile and we build it here https://github.com/Readify/httpstatus/blob/main/.github/workflows/main.yaml#L40

The image is pushed to a private Azure Container Instance (which I use for the Azure hosting), rather than a public one.

@TommasoBianchi would building your own image from source suite your needs, or are you looking for a public image that you can pull?

**Comment by TommasoBianchi** [comment]
> I've just finished upgrading to .NET 6, and in doing so, it's now containerised. To Dockerfile is here https://github.com/Readify/httpstatus/blob/main/src/Teapot.Web/Dockerfile and we build it here https://github.com/Readify/httpstatus/blob/main/.github/workflows/main.yaml#L40
> 
> The image is pushed to a private Azure Container Instance (which I use for the Azure hosting), rather than a public one.

Thank you very much for your work, @aaronpowell!

> @TommasoBianchi would building your own image from source suite your needs, or are you looking for a public image that you can pull?

Ideally, I'd love to be able to pull it directly from a public docker registry, such as the Docker Hub (as a lot of other open source project do).

**Comment by aaronpowell** [comment]
I'll look at what's involved in putting it on the GitHub container registry, that way it's not another set of credentials for me to manage, and it's better linked with this repo for visibility.

(More broadly, I want to overhaul the DevOps pipeline, maybe two birds, one stone 🤔)

**Comment by aaronpowell** [comment]
Done! You can now grab the image from https://github.com/aaronpowell/httpstatus/pkgs/container/httpstatus which is created on every push to `main`, and it's the same image that runs in production (new GitHub Actions workflow tags for ACR and GCR at once).
